export const ZODIAC_PETS = Object.freeze([
  {
    id: 'rat_pet',
    animalKey: 'rat',
    zodiac: '자',
    name: '자쥐',
    title: '별씨앗 수집가',
    color: '#9BADCE',
    accent: '#D7E4FF',
    charm: '별씨앗을 모아 별숨공간 구석구석에 숨겨둬요.',
    passive: { type: 'stardust_find', label: '가끔 별가루를 찾아와요' },
  },
  {
    id: 'ox_pet',
    animalKey: 'ox',
    zodiac: '축',
    name: '축소',
    title: '느긋한 기반지기',
    color: '#C9A66B',
    accent: '#F0D8A5',
    charm: '조용히 오래 머물며 별숨공간의 중심을 단단하게 잡아요.',
    passive: { type: 'stable_production', label: '별가루 생산 흐름 안정' },
  },
  {
    id: 'tiger_pet',
    animalKey: 'tiger',
    zodiac: '인',
    name: '인호',
    title: '용감한 별숲 순찰자',
    color: '#E8B048',
    accent: '#5B3824',
    charm: '별숲을 씩씩하게 뛰어다니며 오늘의 용기를 깨워요.',
    passive: { type: 'mission_bonus', label: '미션 보상 강화' },
  },
  {
    id: 'rabbit_pet',
    animalKey: 'rabbit',
    zodiac: '묘',
    name: '묘토끼',
    title: '달방석의 작은 동행',
    color: '#F4A7C4',
    accent: '#FFE2EF',
    charm: '달빛 사이를 폴짝이며 출석의 별가루를 모아요.',
    passive: { type: 'login_bonus', label: '출석 보상에 별가루 추가' },
  },
  {
    id: 'dragon_pet',
    animalKey: 'dragon',
    zodiac: '진',
    name: '진용',
    title: '별비늘 수호룡',
    color: '#7EC8A4',
    accent: '#D9FFE9',
    charm: '작은 구름을 몰고 다니며 희귀한 오브제를 알아봐요.',
    passive: { type: 'rare_hint', label: '희귀 오브제 발견 감각' },
  },
  {
    id: 'snake_pet',
    animalKey: 'snake',
    zodiac: '사',
    name: '사뱀',
    title: '고요한 수정 감시자',
    color: '#B48EF0',
    accent: '#E8D9FF',
    charm: '수정 둘레를 천천히 감돌며 놓친 별가루를 지켜요.',
    passive: { type: 'offline_save', label: '오프라인 보상 보존' },
  },
  {
    id: 'horse_pet',
    animalKey: 'horse',
    zodiac: '오',
    name: '오말',
    title: '유성길 달림이',
    color: '#D57C58',
    accent: '#FFD5C5',
    charm: '유성길을 달리며 별숨공간에 활기를 불어넣어요.',
    passive: { type: 'activity_bonus', label: '활동 미션 보너스' },
  },
  {
    id: 'goat_pet',
    animalKey: 'goat',
    zodiac: '미',
    name: '미양',
    title: '구름담요 정원사',
    color: '#D9C7A3',
    accent: '#FFF2D7',
    charm: '구름담요를 정리하며 마음이 쉬는 자리를 만들어요.',
    passive: { type: 'diary_bonus', label: '일기 보상 강화' },
  },
  {
    id: 'monkey_pet',
    animalKey: 'monkey',
    zodiac: '신',
    name: '신원숭이',
    title: '반짝 장난꾼',
    color: '#D99A5E',
    accent: '#FFE0B8',
    charm: '높은 오브제 위를 오가며 뜻밖의 선물을 찾아요.',
    passive: { type: 'random_gift', label: '랜덤 선물 발견' },
  },
  {
    id: 'rooster_pet',
    animalKey: 'rooster',
    zodiac: '유',
    name: '유닭',
    title: '새벽별 알림꾼',
    color: '#E86F7A',
    accent: '#FFE1E5',
    charm: '새벽별이 뜨면 가장 먼저 별숨공간을 깨워요.',
    passive: { type: 'morning_check', label: '아침 출석 특화' },
  },
  {
    id: 'dog_pet',
    animalKey: 'dog',
    zodiac: '술',
    name: '술개',
    title: '충직한 별문지기',
    color: '#A47A55',
    accent: '#F3D6B9',
    charm: '문 앞을 지키며 연속 출석의 리듬을 보호해요.',
    passive: { type: 'streak_guard', label: '출석 보호 감각' },
  },
  {
    id: 'pig_pet',
    animalKey: 'pig',
    zodiac: '해',
    name: '해돼지',
    title: '포근한 별저금통',
    color: '#F0A8B8',
    accent: '#FFE3EA',
    charm: '모은 별가루를 포근하게 품고 천천히 불려요.',
    passive: { type: 'storage_bonus', label: '별가루 저장량 증가' },
  },
]);

const PETS_BY_ID = new Map(ZODIAC_PETS.map((pet) => [pet.id, pet]));

export function findZodiacPet(id) {
  return PETS_BY_ID.get(id) || null;
}

